services:
  app:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/hoth/hoth/example.py
    image: ghcr.io/williamjacksn/hoth
    init: true
    ports:
      - 5001:5001
    volumes:
      - ./:/home/python/hoth
    working_dir: /home/python/hoth

  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.13
    init: true
    volumes:
      - ./:/home/python/hoth
    working_dir: /home/python/hoth
